<x-app-layout>
@push('styles')
<link rel="stylesheet" href="{{ asset('xlink-dashboard/dashboard-presets.css') }}">
<link rel="stylesheet" href="{{ asset('xlink-dashboard/dashboard-live.css') }}">
<link rel="stylesheet" href="{{ asset('xlink-dashboard/layout-fixes.css') }}">
<link rel="stylesheet" href="{{ asset('xlink-dashboard/report-ux.css') }}">
<link rel="stylesheet" href="{{ asset('xlink-dashboard/ui-polish-20260826.css') }}">
@endpush
<x-slot name="header">{{ __('Dashboard') }}</x-slot>
@php
$total=(int)($activeCustomerTotal??0); $online=(int)($onlineNow??0); $offline=max(0,$total-$online);
$company=(int)($activeCompany??0); $reseller=(int)($activeReseller??0);
$newToday=\App\Models\CustomersInfo::whereDate('created_at',now()->toDateString())->count();
$newWeek=\App\Models\CustomersInfo::where('created_at','>=',now()->subDays(6)->startOfDay())->count();
$newMonth=\App\Models\CustomersInfo::whereYear('created_at',now()->year)->whereMonth('created_at',now()->month)->count();
$yesterday=(float)\App\Models\CollectionSummary::whereDate('collection_date',now()->subDay()->toDateString())->sum('collection_amount');
$expiring=\App\Models\BillingInfo::join('customers_infos','billing_infos.customer_bill_unique_id','=','customers_infos.customer_unique_id')->whereNull('customers_infos.deleted_at')->where('customers_infos.status','active')->whereNotNull('billing_infos.auto_disable_date')->whereBetween('billing_infos.auto_disable_date',[now()->toDateString(),now()->addDays(7)->toDateString()])->count();
@endphp
<div class="dashboard-shell preset-isp-color-cards size-compact show-subtext" style="--db-cols:4;--db-chart-height:362px">
<div class="dashboard-controlbar"><div><span class="dashboard-kicker">{{ __('X-Link Limited Billing') }}</span><h2>{{ __('Dashboard') }}</h2><p>{{ __('Live operational and billing overview') }}</p></div></div>
<div class="dashboard-card-deck" aria-label="Dashboard cards">
<a class="dashboard-card tone-teal" data-card-key="yesterday_collection" href="{{ route('income-summary') }}"><span class="dashboard-card-icon"><i class="bi bi-calendar2-minus-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Yesterday Collection</span><strong class="dashboard-card-value">{{ number_format($yesterday,2).' ৳' }}</strong><small class="dashboard-card-sub">Verified broadband collection</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-slate" data-card-key="offline_now" href="{{ route('broadband-customers') }}"><span class="dashboard-card-icon"><i class="bi bi-wifi-off"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Offline Now</span><strong class="dashboard-card-value">{{ number_format($offline) }}</strong><small class="dashboard-card-sub">Company '.number_format(max(0,$company-$online)).' • Reseller '.number_format($reseller)</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-cyan" data-card-key="weekly_collection" href="{{ route('income-summary') }}"><span class="dashboard-card-icon"><i class="bi bi-graph-up-arrow"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Weekly Collection</span><strong class="dashboard-card-value">{{ number_format($weekCollection??0,2).' ৳' }}</strong><small class="dashboard-card-sub">PPPoE '.number_format($weekPppoe??0,2).' ৳ • Hotspot '.number_format($weekHotspot??0,2).' ৳</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-indigo" data-card-key="reseller_due" href="{{ route('reseller.dashboard') }}"><span class="dashboard-card-icon"><i class="bi bi-shop-window"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Reseller Due</span><strong class="dashboard-card-value">{{ number_format((float)($resellerDue??0),2).' ৳' }}</strong><small class="dashboard-card-sub">Outstanding partner balance</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-cyan" data-card-key="new_today" href="{{ route('broadband-new-customers') }}"><span class="dashboard-card-icon"><i class="bi bi-person-add"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">New Connections Today</span><strong class="dashboard-card-value">{{ $newToday }}</strong><small class="dashboard-card-sub">Company + Reseller</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-blue" data-card-key="new_this_week" href="{{ route('broadband-new-customers') }}"><span class="dashboard-card-icon"><i class="bi bi-people"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">New Connections This Week</span><strong class="dashboard-card-value">{{ $newWeek }}</strong><small class="dashboard-card-sub">Last 7 days</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-purple" data-card-key="pending_kyc" href="{{ route('income-summary') }}"><span class="dashboard-card-icon"><i class="bi bi-person-vcard-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Pending KYC</span><strong class="dashboard-card-value">{{ 0 }}</strong><small class="dashboard-card-sub">Customer information waiting for review</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-indigo" data-card-key="hotspot_month" href="{{ route('hotspot-dashboard') }}"><span class="dashboard-card-icon"><i class="bi bi-graph-up"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Hotspot Monthly</span><strong class="dashboard-card-value">{{ number_format((float)($monthCollectionHotspot??0),2).' ৳' }}</strong><small class="dashboard-card-sub">Company Hotspot Collection</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-red" data-card-key="expired" href="{{ route('broadband-customers') }}"><span class="dashboard-card-icon"><i class="bi bi-calendar-x-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Expired</span><strong class="dashboard-card-value">{{ number_format($expired??0) }}</strong><small class="dashboard-card-sub">Company + Reseller</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-purple" data-card-key="hotspot_customers" href="{{ route('hotspot-dashboard') }}"><span class="dashboard-card-icon"><i class="bi bi-wifi"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Hotspot Customers</span><strong class="dashboard-card-value">{{ number_format((int)($hotspotCustomers??0)) }}</strong><small class="dashboard-card-sub">Company + Reseller users</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-slate" data-card-key="attendance" href="{{ route('income-summary') }}"><span class="dashboard-card-icon"><i class="bi bi-calendar2-check-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Today Attendance</span><strong class="dashboard-card-value">{{ number_format($attendanceToday??0).' / '.number_format($attendanceTotal??0) }}</strong><small class="dashboard-card-sub">Absent + Late</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-amber" data-card-key="mfs_pending" href="{{ route('income-summary') }}"><span class="dashboard-card-icon"><i class="bi bi-hourglass-split"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">MFS Pending</span><strong class="dashboard-card-value">{{ 0 }}</strong><small class="dashboard-card-sub">Received, matched, failed or waiting</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-green" data-card-key="kyc_approved_month" href="{{ route('income-summary') }}"><span class="dashboard-card-icon"><i class="bi bi-person-check-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">KYC Approved This Month</span><strong class="dashboard-card-value">{{ 0 }}</strong><small class="dashboard-card-sub">Reviewed customer KYC requests</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-green" data-card-key="total_customers" href="{{ route('income-summary') }}"><span class="dashboard-card-icon"><i class="bi bi-person-check-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Active Customers</span><strong class="dashboard-card-value">{{ number_format($total) }}</strong><small class="dashboard-card-sub">Company '.number_format($company).' • Reseller '.number_format($reseller)</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-red" data-card-key="open_tickets" href="{{ route('income-summary') }}"><span class="dashboard-card-icon"><i class="bi bi-ticket-perforated-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Open Tickets</span><strong class="dashboard-card-value">{{ 0 }}</strong><small class="dashboard-card-sub">Open and processing support items</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-green" data-card-key="online_now" href="{{ route('broadband-online-customers') }}"><span class="dashboard-card-icon"><i class="bi bi-wifi"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Online Now</span><strong class="dashboard-card-value">{{ number_format($online) }}</strong><small class="dashboard-card-sub">Live PPPoE sessions</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-amber" data-card-key="hotspot_stock" href="{{ route('hotspot-cards') }}"><span class="dashboard-card-icon"><i class="bi bi-ticket-perforated"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Hotspot Card Stock</span><strong class="dashboard-card-value">{{ number_format($hotspotCardStock??0) }}</strong><small class="dashboard-card-sub">Unused • Active</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-emerald" data-card-key="ap_health" href="{{ route('network-inventory.access-points') }}"><span class="dashboard-card-icon"><i class="bi bi-broadcast-pin"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Access Point Health</span><strong class="dashboard-card-value">{{ number_format($deviceStats['aps_online']??0).' / '.number_format($deviceStats['aps_total']??0) }}</strong><small class="dashboard-card-sub">Online AP / total AP</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-indigo" data-card-key="open_sales_leads" href="{{ route('income-summary') }}"><span class="dashboard-card-icon"><i class="bi bi-funnel-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Open Sales Leads</span><strong class="dashboard-card-value">{{ 0 }}</strong><small class="dashboard-card-sub">Sales queries not converted or lost</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-emerald" data-card-key="router_health" href="{{ route('device-watcher') }}"><span class="dashboard-card-icon"><i class="bi bi-router-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Router Health</span><strong class="dashboard-card-value">{{ number_format($deviceStats['routers_online']??0).' / '.number_format($deviceStats['routers_total']??0) }}</strong><small class="dashboard-card-sub">Online routers / active routers</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-amber" data-card-key="expiring_7d" href="{{ route('broadband-customers') }}"><span class="dashboard-card-icon"><i class="bi bi-calendar-week-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Expiring Next 7 Days</span><strong class="dashboard-card-value">{{ number_format($expiring) }}</strong><small class="dashboard-card-sub">Upcoming billing follow-up</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-red" data-card-key="overdue_tickets" href="{{ route('income-summary') }}"><span class="dashboard-card-icon"><i class="bi bi-alarm-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Tickets Over 24 Hours</span><strong class="dashboard-card-value">{{ 0 }}</strong><small class="dashboard-card-sub">Open workload needing follow-up</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-purple" data-card-key="tickets_today" href="{{ route('income-summary') }}"><span class="dashboard-card-icon"><i class="bi bi-ticket-detailed-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Tickets Created Today</span><strong class="dashboard-card-value">{{ 0 }}</strong><small class="dashboard-card-sub">Complaint, task and sales tickets</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-purple" data-card-key="month_collection" href="{{ route('income-summary') }}"><span class="dashboard-card-icon"><i class="bi bi-calendar2-week-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">This Month Collection</span><strong class="dashboard-card-value">{{ number_format($monthCollection??0,2).' ৳' }}</strong><small class="dashboard-card-sub">PPPoE {{number_format($monthCollectionPppoe??0,2)}} ৳ • Hotspot {{number_format($monthCollectionHotspot??0,2)}} ৳</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-cyan" data-card-key="new_this_month" href="{{ route('broadband-new-customers') }}"><span class="dashboard-card-icon"><i class="bi bi-person-plus-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">New This Month</span><strong class="dashboard-card-value">{{ $newMonth }}</strong><small class="dashboard-card-sub">New customer accounts</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-rose" data-card-key="running_due" href="{{ route('broadband-customers') }}"><span class="dashboard-card-icon"><i class="bi bi-cash-coin"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Running Due</span><strong class="dashboard-card-value">{{ number_format($runningDue??0,2) }} ৳</strong><small class="dashboard-card-sub">Active customer outstanding</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-teal" data-card-key="today_collection" href="{{ route('income-summary') }}"><span class="dashboard-card-icon"><i class="bi bi-wallet2"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Today Collection</span><strong class="dashboard-card-value">{{ number_format($todayCollection??0,2).' ৳' }}</strong><small class="dashboard-card-sub">PPPoE {{ number_format($todayPppoe??0,2) }} ৳ • Hotspot {{ number_format($todayHotspot??0,2) }} ৳</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-amber" data-card-key="locked_disabled" href="{{ route('broadband-customers') }}"><span class="dashboard-card-icon"><i class="bi bi-shield-lock-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">Locked / Disabled</span><strong class="dashboard-card-value">{{ number_format($lockedDisabled??0) }}</strong><small class="dashboard-card-sub">Disabled or temporary</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
<a class="dashboard-card tone-orange" data-card-key="mfs_collection" href="{{ route('income-summary') }}"><span class="dashboard-card-icon"><i class="bi bi-phone-vibrate-fill"></i></span><span class="dashboard-card-copy"><span class="dashboard-card-label">MFS Collection</span><strong class="dashboard-card-value">{{ number_format($mfsCollection??0,2) }} ৳</strong><small class="dashboard-card-sub">Digital + SMS banking (month)</small></span><i class="bi bi-arrow-up-right dashboard-card-open"></i></a>
</div>

<div class="dashboard-panels" id="dashboardMasonryPanels">
<section class="dashboard-panel dashboard-masonry-item panel-analysis"><header><div><span>Subscriber Health</span><h3>Customer Account Analysis</h3></div><a href="{{route('broadband-customers')}}">Customer list <i class="bi bi-arrow-right"></i></a></header><div class="customer-ring-wrap"><div class="customer-ring-canvas"><canvas id="customerRingChart"></canvas><div class="ring-center"><small>Active</small><strong>{{number_format($total)}}</strong></div></div><div class="ring-metrics"><a class="ring-metric"><i class="ring-dot"></i><span>Total</span><strong>{{number_format($customersData['total']??0)}}</strong></a><a class="ring-metric active"><i class="ring-dot"></i><span>Active</span><strong>{{number_format($customersData['active']??0)}}</strong></a><a class="ring-metric"><i class="ring-dot"></i><span>Pending</span><strong>{{number_format($customersData['pending']??0)}}</strong></a><a class="ring-metric"><i class="ring-dot"></i><span>Free</span><strong>{{number_format($customersData['free']??0)}}</strong></a><a class="ring-metric"><i class="ring-dot"></i><span>Temporary Disable</span><strong>{{number_format($customersData['temporary_disable']??0)}}</strong></a><a class="ring-metric"><i class="ring-dot"></i><span>Inactive</span><strong>{{number_format($customersData['inactive']??0)}}</strong></a><a class="ring-metric"><i class="ring-dot"></i><span>Recent</span><strong>{{number_format($customersData['recent']??0)}}</strong></a></div></div></section>
<section class="dashboard-panel dashboard-masonry-item panel-operations"><header><div><span>Billing Forecast</span><h3>Billing Health</h3></div><a href="{{route('income-summary')}}">Finance report <i class="bi bi-arrow-right"></i></a></header><div class="analysis-metric-list"><a href="{{route('income-summary')}}"><span>This Month Collection</span><strong>{{number_format($monthCollection??0,2)}} ৳</strong></a><a class="danger" href="{{route('broadband-due-customers')}}"><span>Running Due</span><strong>{{number_format($runningDue??0,2)}} ৳</strong></a><a href="{{route('broadband-due-customers')}}"><span>Expiring Next 7 Days</span><strong>{{$expiring}}</strong></a></div></section>
<section class="dashboard-panel dashboard-masonry-item panel-operations"><header><div><span>Business Split</span><h3>Company vs Reseller Split</h3></div><a href="{{route('reseller.dashboard')}}">Partner network <i class="bi bi-arrow-right"></i></a></header><div class="analysis-metric-list"><a href="{{route('broadband-customers')}}"><span>Company Customers</span><strong>{{$company}}</strong></a><a href="{{route('reseller.dashboard')}}"><span>Reseller Customers</span><strong>{{$reseller}}</strong></a><a href="{{route('income-summary')}}"><span>Company Collection</span><strong>{{number_format($monthCollectionPppoe??0,2)}} ৳</strong></a><a href="{{route('reseller.dashboard')}}"><span>Reseller Due</span><strong>{{number_format($resellerDue??0,2)}} ৳</strong></a></div></section>
<section class="dashboard-panel dashboard-masonry-item panel-ticket-overview"><header><div><span>Support Workload</span><h3>Ticket Overview</h3></div></header><div class="operation-grid"><a href="#"><i class="bi bi-ticket"></i><span>Open</span><strong>0</strong></a><a href="#"><i class="bi bi-alarm"></i><span>Over 24 Hours</span><strong>0</strong></a><a href="#"><i class="bi bi-plus-circle"></i><span>Today</span><strong>0</strong></a><a href="#"><i class="bi bi-person-vcard"></i><span>Pending KYC</span><strong>0</strong></a></div></section>
<section class="dashboard-panel dashboard-masonry-item panel-new-connections"><header><div><span>Subscriber Growth</span><h3>New Connection Graph</h3></div></header><div class="dashboard-chart-shell"><canvas id="newConnectionChart"></canvas></div></section>
<section class="dashboard-panel dashboard-masonry-item panel-revenue"><header><div><span>Income Mix</span><h3>Monthly Collection Analysis</h3></div></header><div class="dashboard-chart-shell"><canvas id="revenueMixChart"></canvas></div><div class="revenue-summary"><span><i class="broadband"></i>Broadband <strong>{{number_format($monthCollectionPppoe??0,2)}} ৳</strong></span><span><i class="hotspot"></i>Hotspot <strong>{{number_format($monthCollectionHotspot??0,2)}} ৳</strong></span></div></section>
<section class="dashboard-panel dashboard-masonry-item panel-recent"><header><div><span>Ledger Activity</span><h3>Recent Transactions</h3></div><div class="d-flex gap-1"><a href="{{route('ledger-summary')}}">Broadband</a><a href="{{route('hotspot-ledger')}}">Hotspot</a></div></header><div class="table-responsive"><table class="table table-hover align-middle mb-0 dashboard-recent-table"><thead><tr><th>Customer / Source</th><th>Type</th><th class="text-end">Amount</th></tr></thead><tbody>@forelse($recentTransactions as $tx)<tr><td><div class="fw-semibold">{{optional($tx->customer)->customer_name??$tx->customer_collection_unique_id}}</div><div class="small text-secondary">{{$tx->collection_date}}</div></td><td><span class="badge text-bg-success">{{$tx->payment_type??'collection'}}</span></td><td class="text-end fw-bold">{{number_format((float)$tx->collection_amount,2)}} ৳</td></tr>@empty<tr><td colspan="3" class="text-center text-secondary py-4">No recent transaction found.</td></tr>@endforelse</tbody></table></div></section>
<section class="dashboard-panel dashboard-masonry-item panel-operations panel-span-full"><header><div><span>System Status</span><h3>Operational Overview</h3></div></header><div class="operation-grid"><a href="{{route('device-watcher')}}"><i class="bi bi-router"></i><span>Routers</span><strong>{{($deviceStats['routers_online']??0)}} / {{($deviceStats['routers_total']??0)}}</strong></a><a href="#"><i class="bi bi-ticket"></i><span>Open Tickets</span><strong>0</strong></a><a href="#"><i class="bi bi-person-vcard"></i><span>Pending KYC</span><strong>0</strong></a><a href="{{route('income-summary')}}"><i class="bi bi-phone"></i><span>MFS Pending</span><strong>0</strong></a></div></section>
</div></div>
@push('scripts')
<script src="{{ asset('xlink-dashboard/chart.umd.min.js.download') }}"></script>
@php
$customerChartValues=json_encode([$customersData['total']??0,$customersData['active']??0,$customersData['pending']??0,$customersData['free']??0,$customersData['temporary_disable']??0,$customersData['inactive']??0,$customersData['recent']??0]);
$newConnectionValues=json_encode($newConnections);
$revenueValues=json_encode([(float)($monthCollectionPppoe??0),(float)($monthCollectionHotspot??0)]);
@endphp
<script>
document.addEventListener('DOMContentLoaded',function(){
const m=(id,c)=>{const e=document.getElementById(id);if(e&&window.Chart)new Chart(e,c)};
const v={!!$customerChartValues!!};
m('customerRingChart',{type:'doughnut',data:{labels:['Total','Active','Pending','Free','Temporary Disable','Inactive','Recent'],datasets:[{data:v}]},options:{responsive:true,maintainAspectRatio:false,cutout:'68%',plugins:{legend:{display:false}}}});
const n={!!$newConnectionValues!!};
m('newConnectionChart',{type:'bar',data:{labels:Object.keys(n),datasets:[{data:Object.values(n).map(x=>Number(x.total||0)),borderRadius:6}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true}},plugins:{legend:{display:false}}}});
m('revenueMixChart',{type:'doughnut',data:{labels:['Broadband','Hotspot'],datasets:[{data:{!!$revenueValues!!}}]},options:{responsive:true,maintainAspectRatio:false,cutout:'68%',plugins:{legend:{display:false}}}});
});
</script>
@endpush
</x-app-layout>