<x-app-layout>
@push('styles')
<link rel="stylesheet" href="{{ asset('xlink-broadband/customers.css') }}">
<link rel="stylesheet" href="{{ asset('xlink-broadband/ui-polish-20260826.css') }}">
@endpush
<div class="container-fluid py-2">
<div class="d-flex justify-content-between align-items-center mb-3"><div><span class="text-uppercase small text-muted fw-semibold">Broadband</span><h3 class="mb-0">{{ $mode==='due'?'Due Customers':($mode==='inactive'?'Inactive Customers':($mode==='unverified'?'Unverified Customers':($mode==='online'?'Online Customers':'Customer List'))) }}</h3><small class="text-muted">{{ $mode==='due'?'Outstanding customer balances':($mode==='inactive'?'No recent online activity':($mode==='unverified'?'Missing mobile, NID or GPS location':'Broadband customer operations')) }}</small></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="{{ route('customer-add') }}">Add Customer</a><a class="btn btn-primary" href="{{ route('broadband-packages') }}">Packages</a></div></div>
<div class="card shadow-sm border-0 mb-3"><div class="card-body"><form class="row g-2" method="GET"><div class="col-md-3"><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Customer ID, name or mobile"></div><div class="col-md-2"><select class="form-select" name="router_id"><option value="">All Routers</option>@foreach($routers as $r)<option value="{{ $r->router_name }}" @selected(request('router_id')===$r->router_name)>{{ $r->router_name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="rows"><option>50</option><option>100</option><option>250</option><option>500</option></select></div><div class="col-md-5 d-flex gap-2"><button class="btn btn-primary">Search</button><a class="btn btn-outline-secondary" href="{{ url()->current() }}">Reset</a></div></form></div></div>
<div class="card shadow-sm border-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>CID</th><th>Customer</th><th>PPPoE / IP</th><th>Mobile</th><th>Package</th><th>Router</th><th>Billing</th><th>Address</th><th>Status</th></tr></thead><tbody>
@forelse($customers as $c)
<tr><td><span class="badge bg-secondary">{{ $c->customer_unique_id }}</span></td><td><strong>{{ $c->customer_name }}</strong><br><small class="text-muted">{{ $c->contact_email ?: '—' }}</small></td><td>{{ $c->pppUser->username ?? ($c->pppUser->ppp_remote_ip ?? '—') }}</td><td>{{ $c->mobile ?: '—' }}</td><td>{{ $c->package->package ?? $c->pppUser->package_name ?? '—' }}</td><td>{{ $c->pppUser->router_name ?? '—' }}</td><td><div>Bill: {{ number_format($c->billing?->total_amount ?? 0,2) }} ৳</div><div class="text-danger">Due: {{ number_format($c->billing?->due_amount ?? 0,2) }} ৳</div></td><td>{{ $c->customerAddress->map(fn($a)=>implode(', ',array_filter([$a->input_type_text,$a->input_type_dropdown,$a->input_type_textarea])))->filter()->implode(', ') ?: '—' }}</td><td><span class="badge text-bg-{{ in_array($c->status,['active','online'])?'success':(in_array($c->status,['inactive','disable'])?'secondary':'warning') }}">{{ ucfirst($c->status ?: 'unknown') }}</span></td></tr>
@empty<tr><td colspan="9" class="text-center py-5">No customers found.</td></tr>@endforelse
</tbody></table></div><div class="card-footer d-flex justify-content-between align-items-center"><span>{{ $customers->total() }} records</span>{{ $customers->links() }}</div></div>
</div>
</x-app-layout>
