<?php

namespace App\Http\Controllers;

use App\Models\TeamAttendanceDevice; use App\Models\TeamAttendanceLocation; use App\Models\TeamAttendanceRecord;
use App\Models\TeamAttendanceSetting; use App\Models\TeamConveyanceClaim; use App\Models\TeamLeaveRequest;
use App\Models\TeamPayrollRecord; use App\Models\TeamVisit; use App\Models\User; use App\Models\CustomersInfo;
use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;

class TeamAccessController extends Controller
{
    private function adminGate(string $permission='view-user'): void { $u=auth()->user(); if(!$u || (!$u->hasRole('Super Admin') && !$u->can($permission))) abort(403,'Unauthorized action.'); }
    public function overview(){ $this->adminGate(); return view('xlink.team-access', ['users'=>User::count(),'roles'=>class_exists(\Spatie\Permission\Models\Role::class)?\Spatie\Permission\Models\Role::count():0,'superAdmins'=>User::role('Super Admin')->count(),'twoFactor'=>User::whereNotNull('two_factor_confirmed_at')->count(),'recentUsers'=>User::latest()->limit(8)->get()]); }
    public function teamOverview(){ $this->adminGate(); $users=User::with('roles')->whereDoesntHave('roles',fn($q)=>$q->where('name','Reseller'))->orderBy('name')->get(); return view('xlink.team-access.page', ['page'=>'Team Overview','users'=>$users,'stats'=>[['Staff',$users->count()],['Admins',$users->filter(fn($u)=>$u->hasRole('Super Admin'))->count()],['2FA',$users->filter(fn($u)=>$u->two_factor_confirmed_at)->count()],['Teams',\App\Models\Team::count()]]]); }
    public function attendance(){ $u=auth()->user(); $record=TeamAttendanceRecord::firstOrNew(['user_id'=>$u->id,'attendance_date'=>today()]); return view('xlink.team-access.page', ['page'=>'Attendance','record'=>$record,'today'=>today()->toDateString(),'settings'=>TeamAttendanceSetting::find(1),'users'=>collect()]); }
    public function checkIn(Request $r){ $u=auth()->user(); $record=TeamAttendanceRecord::firstOrCreate(['user_id'=>$u->id,'attendance_date'=>today()]); if(!$record->check_in_at){$record->check_in_at=now();$record->check_in_lat=$r->input('lat');$record->check_in_lng=$r->input('lng');$record->status='present';$record->note=$r->input('note');$record->save();} return back()->with('success','Attendance check-in recorded.'); }
    public function checkOut(Request $r){ $u=auth()->user(); $record=TeamAttendanceRecord::where(['user_id'=>$u->id,'attendance_date'=>today()])->first(); if(!$record || !$record->check_in_at) return back()->with('error','Please check in first.'); $record->check_out_at=now();$record->check_out_lat=$r->input('lat');$record->check_out_lng=$r->input('lng');$record->save(); return back()->with('success','Attendance check-out recorded.'); }
    public function attendanceReport(Request $r){ $this->adminGate(); $from=$r->input('from',today()->startOfMonth()->toDateString());$to=$r->input('to',today()->toDateString()); $q=TeamAttendanceRecord::with('user')->whereBetween('attendance_date',[$from,$to]); if($r->filled('user_id'))$q->where('user_id',$r->user_id); if($r->filled('status'))$q->where('status',$r->status); if($r->filled('q'))$q->whereHas('user',fn($x)=>$x->where('name','like','%'.$r->q.'%')); return view('xlink.team-access.page',['page'=>'Attendance Report','records'=>$q->orderByDesc('attendance_date')->paginate(25)->withQueryString(),'users'=>User::orderBy('name')->get()]); }
    public function attendanceSettings(){ $this->adminGate('edit-user'); return view('xlink.team-access.page',['page'=>'Attendance Settings','settings'=>TeamAttendanceSetting::find(1),'devices'=>TeamAttendanceDevice::latest()->get(),'locations'=>TeamAttendanceLocation::latest()->get()]); }
    public function saveAttendanceSettings(Request $r){ $this->adminGate('edit-user'); $s=TeamAttendanceSetting::findOrFail(1); $s->fill($r->validate(['office_start'=>'required','office_end'=>'required','late_grace_minutes'=>'required|integer|min:0|max:240','location_mode'=>'required|in:record,enforce','radius_mode'=>'required|in:record,enforce','selfie_enabled'=>'nullable|boolean','selfie_checkin'=>'required|in:required,optional','selfie_checkout'=>'required|in:required,optional','selfie_retention_days'=>'required|integer|min:1|max:3650'])); $s->weekly_off=$r->input('weekly_off',[]);$s->selfie_enabled=$r->boolean('selfie_enabled');$s->save(); return back()->with('success','Attendance policy saved.'); }
    public function storeDevice(Request $r){ $this->adminGate('edit-user'); TeamAttendanceDevice::create($r->validate(['device_name'=>'required|max:255','device_type'=>'required|max:100','device_ip'=>'required|max:255','device_port'=>'required|integer','device_location'=>'nullable|max:255'])); return back()->with('success','Attendance device added.'); }
    public function storeLocation(Request $r){ $this->adminGate('edit-user'); TeamAttendanceLocation::create($r->validate(['location_name'=>'required|max:255','lat'=>'required|numeric','lng'=>'required|numeric','radius_m'=>'required|integer|min:1'])); return back()->with('success','Attendance location added.'); }
    public function leaves(Request $r){ $u=auth()->user(); $this->adminGate(); $q=TeamLeaveRequest::with(['user','approver']); if($r->filled('user_id'))$q->where('user_id',$r->user_id); if($r->filled('status'))$q->where('status',$r->status); if($r->filled('from'))$q->whereDate('from_date','>=',$r->from); if($r->filled('to'))$q->whereDate('to_date','<=',$r->to); return view('xlink.team-access.page',['page'=>'Leave Management','leaves'=>$q->latest()->paginate(25)->withQueryString(),'users'=>User::orderBy('name')->get()]); }
    public function submitLeave(Request $r){ $r->validate(['leave_type'=>'required|max:100','from_date'=>'required|date','to_date'=>'required|date|after_or_equal:from_date','reason'=>'nullable|string|max:2000']); TeamLeaveRequest::create(['user_id'=>auth()->id(),'leave_type'=>$r->leave_type,'from_date'=>$r->from_date,'to_date'=>$r->to_date,'reason'=>$r->reason]); return back()->with('success','Leave request submitted.'); }
    public function updateLeave(Request $r, TeamLeaveRequest $leave){ $this->adminGate('edit-user'); $status=$r->validate(['status'=>'required|in:approved,rejected,cancelled'])['status']; $leave->update(['status'=>$status,'approved_by'=>auth()->id()]); return back()->with('success','Leave status updated.'); }
    public function payroll(Request $r){ $this->adminGate(); $month=$r->input('month',today()->startOfMonth()->toDateString()); $q=TeamPayrollRecord::with('user')->where('month',$month); if($r->filled('user_id'))$q->where('user_id',$r->user_id); return view('xlink.team-access.page',['page'=>'Payroll & Salary','payroll'=>$q->get(),'users'=>User::orderBy('name')->get(),'month'=>$month]); }
    public function savePayroll(Request $r){ $this->adminGate('edit-user'); $data=$r->validate(['user_id'=>'required|exists:users,id','month'=>'required|date','base_salary'=>'required|numeric|min:0','allowances'=>'nullable|numeric|min:0','bonus'=>'nullable|numeric|min:0','deductions'=>'nullable|numeric|min:0','status'=>'required|in:draft,paid']); $data['net_salary']=($data['base_salary']+($data['allowances']??0)+($data['bonus']??0))-($data['deductions']??0); TeamPayrollRecord::updateOrCreate(['user_id'=>$data['user_id'],'month'=>$data['month']],$data); return back()->with('success','Payroll record saved.'); }
    public function visits(Request $r){ $this->adminGate(); $q=TeamVisit::with(['user','customer']); if($r->filled('user_id'))$q->where('user_id',$r->user_id); return view('xlink.team-access.page',['page'=>'Visits & Conveyance','visits'=>$q->latest('visited_at')->paginate(20)->withQueryString(),'claims'=>TeamConveyanceClaim::with('user')->latest()->paginate(20,['*'],'claims_page')->withQueryString(),'users'=>User::orderBy('name')->get()]); }
    public function checkVisit(Request $r){ $data=$r->validate(['visit_type'=>'required|max:100','customer_id'=>'nullable|exists:customers_infos,id','purpose'=>'nullable|max:255','note'=>'nullable|string|max:2000','lat'=>'nullable|numeric','lng'=>'nullable|numeric']); TeamVisit::create($data+['user_id'=>auth()->id(),'visited_at'=>now()]); return back()->with('success','Visit check-in recorded.'); }
    public function submitClaim(Request $r){ $data=$r->validate(['claim_date'=>'required|date','from_place'=>'required|max:255','to_place'=>'required|max:255','purpose'=>'required|max:255','amount'=>'required|numeric|min:0.01','note'=>'nullable|string|max:2000']); TeamConveyanceClaim::create($data+['user_id'=>auth()->id()]); return back()->with('success','Conveyance claim submitted.'); }
    public function reviewClaim(Request $r, TeamConveyanceClaim $claim){ $this->adminGate('edit-user'); $status=$r->validate(['status'=>'required|in:approved,rejected'])['status']; $claim->update(['status'=>$status,'reviewed_by'=>auth()->id()]); return back()->with('success','Conveyance claim updated.'); }
    public function demo(){ $this->adminGate(); return view('xlink.team-access.page',['page'=>'Demo Module']); }
}
