<x-app-layout>
<x-slot name="header"><div class="d-flex align-items-center gap-2"><i class="bi bi-arrow-left-right text-primary"></i><span>{{ __('Partner Cashflow') }}</span></div></x-slot>
<div class="container-fluid py-4">
  <div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3"><div><h3 class="mb-1">{{ __('Cashflow') }}</h3><small class="text-muted">{{ $from }} → {{ $to }}</small></div><a href="{{ route('reseller-ledger',['from'=>$from,'to'=>$to]) }}" class="btn btn-outline-primary"><i class="bi bi-journal-check me-1"></i>{{ __('Open Ledger') }}</a></div>
  <form class="card border-0 shadow-sm mb-3"><div class="card-body row g-2 align-items-end"><div class="col-md-3"><label class="form-label">{{ __('From') }}</label><input class="form-control" type="date" name="from" value="{{ $from }}"></div><div class="col-md-3"><label class="form-label">{{ __('To') }}</label><input class="form-control" type="date" name="to" value="{{ $to }}"></div><div class="col-md-3"><label class="form-label">{{ __('Partner') }}</label><select class="form-select" name="reseller_id"><option value="">{{ __('All Partners') }}</option>@foreach($resellers as $r)<option value="{{ $r->id }}" @selected((string)$r->id===(string)$resellerId)>{{ $r->user->name ?? ('Partner #'.$r->id) }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-primary w-100">{{ __('Apply') }}</button></div></div></form>
  <div class="row g-3 mb-4"><div class="col-md-6"><div class="card border-0 shadow-sm"><div class="card-body"><div class="text-muted small">{{ __('Incoming') }}</div><div class="fs-2 fw-bold text-success">৳{{ number_format($stats['incoming'],2) }}</div></div></div></div><div class="col-md-6"><div class="card border-0 shadow-sm"><div class="card-body"><div class="text-muted small">{{ __('Spend / Debit') }}</div><div class="fs-2 fw-bold text-danger">৳{{ number_format($stats['spend'],2) }}</div></div></div></div></div>
  <div class="card shadow-sm"><div class="card-header fw-semibold">{{ __('Recent Partner Cashflow') }}</div><div class="table-responsive"><table class="table table-sm table-hover align-middle mb-0"><thead><tr><th>{{ __('Date') }}</th><th>{{ __('Partner') }}</th><th>{{ __('Customer') }}</th><th>{{ __('Type') }}</th><th>{{ __('Method') }}</th><th>{{ __('Amount') }}</th></tr></thead><tbody>
  @forelse($collections as $row)<tr><td>{{ $row->collection_date?->format('Y-m-d H:i') }}</td><td>{{ optional(optional($row->customer)->reseller)->user->name ?? 'Partner' }}</td><td>{{ optional($row->customer)->customer_name ?? optional($row->customer)->customer_unique_id }}</td><td><span class="badge text-bg-success">Incoming</span></td><td>{{ $row->payment_method ?? 'collection' }}</td><td class="text-end fw-semibold text-success">৳{{ number_format($row->collection_amount,2) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">{{ __('No customer collections found.') }}</td></tr>@endforelse
  @foreach($wallet as $row)<tr><td>{{ $row->created_at?->format('Y-m-d H:i') }}</td><td>{{ optional($row->reseller->user)->name ?? 'Partner' }}</td><td>-</td><td><span class="badge {{ $row->type==='credit' ? 'text-bg-success' : 'text-bg-danger' }}">{{ $row->type==='credit' ? 'Incoming' : 'Spend' }}</span></td><td>{{ $row->reference_type ?? 'wallet' }}</td><td class="text-end fw-semibold {{ $row->type==='credit' ? 'text-success' : 'text-danger' }}">৳{{ number_format($row->amount,2) }}</td></tr>@endforeach
  </tbody></table></div></div>
</div></x-app-layout>
