<x-app-layout>
<x-slot name="header"><div class="d-flex align-items-center gap-2"><i class="bi bi-journal-check text-info"></i><span>{{ __('Partner Ledger') }}</span></div></x-slot>
<div class="container-fluid py-4">
  <div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3"><div><h3 class="mb-1">{{ __('Partner Credit & Spend Ledger') }}</h3><small class="text-muted">{{ $from }} → {{ $to }} · {{ number_format($total) }} {{ __('entries') }}</small></div><a class="btn btn-outline-success" href="{{ request()->fullUrlWithQuery(['export'=>1]) }}"><i class="bi bi-download me-1"></i>{{ __('CSV Export') }}</a></div>
  <form class="card border-0 shadow-sm mb-3"><div class="card-body row g-2 align-items-end"><div class="col-md-2"><label class="form-label">{{ __('From Date') }}</label><input class="form-control" type="date" name="from" value="{{ $from }}"></div><div class="col-md-2"><label class="form-label">{{ __('To Date') }}</label><input class="form-control" type="date" name="to" value="{{ $to }}"></div><div class="col-md-2"><label class="form-label">{{ __('Partner') }}</label><select class="form-select" name="reseller_id"><option value="">{{ __('All') }}</option>@foreach($resellers as $r)<option value="{{ $r->id }}" @selected((string)$r->id===(string)$resellerId)>{{ $r->user->name ?? ('#'.$r->id) }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">{{ __('Type') }}</label><select class="form-select" name="type"><option value="all" @selected($type==='all')>{{ __('All') }}</option><option value="incoming" @selected($type==='incoming')>{{ __('Incoming') }}</option><option value="spend" @selected($type==='spend')>{{ __('Spend') }}</option></select></div><div class="col-md-3"><label class="form-label">{{ __('Search') }}</label><input class="form-control" name="q" value="{{ $search }}" placeholder="{{ __('Partner, customer, reference…') }}"></div><div class="col-md-1"><button class="btn btn-primary w-100"><i class="bi bi-search"></i></button></div></div></form>
  <div class="row g-3 mb-3"><div class="col-md-6"><div class="card shadow-sm"><div class="card-body"><small class="text-muted">{{ __('Incoming') }}</small><div class="fs-4 fw-bold text-success">৳{{ number_format($incomingTotal,2) }}</div></div></div></div><div class="col-md-6"><div class="card shadow-sm"><div class="card-body"><small class="text-muted">{{ __('Spend') }}</small><div class="fs-4 fw-bold text-danger">৳{{ number_format($spendTotal,2) }}</div></div></div></div></div>
  <div class="card shadow-sm"><div class="table-responsive"><table class="table table-sm table-hover align-middle mb-0"><thead class="table-light"><tr><th>Date / Time</th><th>Reseller</th><th>Customer</th><th>Type</th><th>Method / Ref</th><th>Details / By</th><th class="text-end">Amount</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ \Carbon\Carbon::parse($row['date'])->format('Y-m-d H:i') }}</td><td class="fw-semibold">{{ $row['reseller'] }}</td><td>{{ $row['customer'] }}</td><td><span class="badge {{ $row['type']==='incoming'?'text-bg-success':'text-bg-danger' }}">{{ ucfirst($row['type']) }}</span></td><td>{{ $row['method'] }} / <code>{{ $row['reference'] }}</code></td><td>{{ $row['details'] }} <span class="text-muted">/ {{ $row['by'] }}</span></td><td class="text-end fw-semibold {{ $row['type']==='incoming'?'text-success':'text-danger' }}">৳{{ number_format($row['amount'],2) }}</td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">{{ __('No ledger entries found.') }}</td></tr>@endforelse</tbody></table></div>
  @if($pages>1)<div class="card-footer d-flex justify-content-between align-items-center"><small class="text-muted">{{ __('Page') }} {{ $page }} / {{ $pages }}</small><div class="btn-group">@for($p=1;$p<=$pages;$p++)<a class="btn btn-sm {{ $p===$page?'btn-primary':'btn-outline-secondary' }}" href="{{ request()->fullUrlWithQuery(['page'=>$p,'export'=>null]) }}">{{ $p }}</a>@endfor</div></div>@endif
  </div>
</div>
</x-app-layout>
