<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\BandwidthInvoice; use App\Models\BandwidthReseller; use App\Models\BandwidthService; use App\Models\BandwidthTicket;
use Illuminate\Http\Request;
class BandwidthResellerController extends Controller {
 private function guard(string $p): void {abort_unless(hasAccess(['Super Admin'],[$p]),403);}
 private function view(string $mode,array $data=[]){return view('bandwidth-reseller.index',array_merge(compact('mode'),$data));}
 public function index(Request $r){$this->guard('bandwidth-reseller');$q=BandwidthReseller::withCount('services','tickets');if($r->q)$q->where(fn($x)=>$x->where('company','like','%'.$r->q.'%')->orWhere('code','like','%'.$r->q.'%')->orWhere('contact_name','like','%'.$r->q.'%'));if($r->status)$q->where('status',$r->status);$resellers=$q->orderBy('company')->paginate(25)->withQueryString();return $this->view('resellers',compact('resellers'));}
 public function store(Request $r){$this->guard('bandwidth-reseller');$d=$r->validate(['code'=>'required|max:40|unique:bandwidth_resellers,code','company'=>'required|max:255','contact_name'=>'required|max:255','email'=>'nullable|email','phone'=>'required|max:30','username'=>'nullable|max:120','monthly_due'=>'required|numeric|min:0','credit_balance'=>'required|numeric|min:0','billing_day'=>'required|integer|min:1|max:28','status'=>'required|in:active,suspended','notes'=>'nullable']);BandwidthReseller::create($d);return back()->with('success','Bandwidth reseller added.');}
 public function update(Request $r,BandwidthReseller $bandwidthReseller){$this->guard('bandwidth-reseller');$d=$r->validate(['code'=>'required|max:40|unique:bandwidth_resellers,code,'.$bandwidthReseller->id,'company'=>'required|max:255','contact_name'=>'required|max:255','email'=>'nullable|email','phone'=>'required|max:30','username'=>'nullable|max:120','monthly_due'=>'required|numeric|min:0','credit_balance'=>'required|numeric|min:0','billing_day'=>'required|integer|min:1|max:28','status'=>'required|in:active,suspended','notes'=>'nullable']);$bandwidthReseller->update($d);return back()->with('success','Bandwidth reseller updated.');}
 public function destroy(BandwidthReseller $bandwidthReseller){$this->guard('bandwidth-reseller');$bandwidthReseller->delete();return back()->with('success','Bandwidth reseller removed.');}
 public function services(){ $this->guard('bandwidth-services');$services=BandwidthService::with('reseller')->latest()->paginate(25);$resellers=BandwidthReseller::orderBy('company')->get();return $this->view('services',compact('services','resellers'));}
 public function storeService(Request $r){$this->guard('bandwidth-services');BandwidthService::create($r->validate(['bandwidth_reseller_id'=>'required|exists:bandwidth_resellers,id','name'=>'required|max:255','service_type'=>'required|max:80','monthly_charge'=>'required|numeric|min:0','status'=>'required|in:active,disabled','notes'=>'nullable']));return back()->with('success','Service added.');}
 public function toggleService(BandwidthService $service){$this->guard('bandwidth-services');$service->update(['status'=>$service->status==='active'?'disabled':'active']);return back();}
 public function invoices(Request $r){$this->guard('bandwidth-billing');$q=BandwidthInvoice::with('reseller')->latest('billing_month');if($r->reseller_id)$q->where('bandwidth_reseller_id',$r->reseller_id);if($r->status)$q->where('status',$r->status);$invoices=$q->paginate(25)->withQueryString();$resellers=BandwidthReseller::orderBy('company')->get();return $this->view('invoices',compact('invoices','resellers'));}
 public function storeInvoice(Request $r){$this->guard('bandwidth-billing');$d=$r->validate(['bandwidth_reseller_id'=>'required|exists:bandwidth_resellers,id','billing_month'=>'required|date','due_date'=>'required|date','total_amount'=>'required|numeric|min:0.01','notes'=>'nullable']);$d['invoice_no']='BW-'.now()->format('Ym').'-'.str_pad((string)(BandwidthInvoice::max('id')+1),5,'0',STR_PAD_LEFT);BandwidthInvoice::create($d);return back()->with('success','Invoice created.');}
 public function payInvoice(Request $r,BandwidthInvoice $invoice){$this->guard('bandwidth-billing');$a=$r->validate(['amount'=>'required|numeric|min:0.01'])['amount'];$invoice->paid_amount=min((float)$invoice->total_amount,(float)$invoice->paid_amount+(float)$a);$invoice->status=$invoice->paid_amount>=(float)$invoice->total_amount?'paid':($invoice->paid_amount>0?'partial':'unpaid');$invoice->save();return back()->with('success','Invoice payment recorded.');}
 public function tickets(Request $r){$this->guard('bandwidth-support');$q=BandwidthTicket::with('reseller')->latest();if($r->status)$q->where('status',$r->status);if($r->q)$q->where('subject','like','%'.$r->q.'%');$tickets=$q->paginate(25)->withQueryString();$resellers=BandwidthReseller::orderBy('company')->get();return $this->view('tickets',compact('tickets','resellers'));}
 public function storeTicket(Request $r){$this->guard('bandwidth-support');$d=$r->validate(['bandwidth_reseller_id'=>'required|exists:bandwidth_resellers,id','subject'=>'required|max:255','description'=>'required','priority'=>'required|in:low,normal,high,urgent','status'=>'required|in:new,open,pending,closed','assigned_to'=>'nullable|max:255']);$d['ticket_no']=BandwidthTicket::nextNo();BandwidthTicket::create($d);return back()->with('success','Support ticket created.');}
 public function updateTicket(Request $r,BandwidthTicket $ticket){$this->guard('bandwidth-support');$ticket->update($r->validate(['status'=>'required|in:new,open,pending,closed','priority'=>'required|in:low,normal,high,urgent','assigned_to'=>'nullable|max:255']));return back()->with('success','Ticket updated.');}
}